version: '3'

tasks:
  test:
    desc: "バックエンドテスト"
    cmds:
      - go test -v ./internal/...

  dev-start:
    desc: "開発用実行"
    cmds:
      - go run ./cmd/backend/main.go

  build:
    desc: "バイナリビルド"
    cmds:
      - go build -o ../bin/backend ./cmd/backend/main.go

  start:
    desc: "ビルドバイナリ実行"
    cmds:
      - ../bin/backend
