worker_processes auto;

events {
    worker_connections 1024;
}

pid /tmp/nginx.pid;

http {
    client_body_temp_path /tmp/client_temp;
    proxy_temp_path       /tmp/proxy_temp;
    fastcgi_temp_path     /tmp/fastcgi_temp;
    uwsgi_temp_path       /tmp/uwsgi_temp;
    scgi_temp_path        /tmp/scgi_temp;

    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    access_log /dev/stdout;
    error_log /dev/stderr;

    sendfile        on;
    keepalive_timeout 65;
    types_hash_max_size 2048;
    gzip on;

    server {
        listen 0.0.0.0:80;
        listen [::]:80;
        server_name _;

        # ビューワーページ配信用
        root /www/html;
        index index.html;

        location / {
            try_files $uri $uri/ =404;
            autoindex on;
        }

        # BFF へのリバースプロキシ
        location /users {
            proxy_pass http://host.docker.internal:3000; # ホストマシンで動くBFFへ転送
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
